In [27]:
import sqlite3                                 
import pandas as pd                             
 
con = sqlite3.connect('../data/raw/airtel.db')  
 
def q(sql):                                     
    return pd.read_sql(sql, con)

In [28]:
q("""SELECT * from circles;""")

    circle_id           circle_name region
0           1                 Delhi  North
1           2                Punjab  North
2           3               Haryana  North
3           4      Himachal Pradesh  North
4           5       Jammu & Kashmir  North
5           6             Rajasthan  North
6           7  Uttar Pradesh (East)  North
7           8  Uttar Pradesh (West)  North
8           9                Mumbai   West
9          10           Maharashtra   West
10         11               Gujarat   West
11         12        Madhya Pradesh   West
12         13        Andhra Pradesh  South
13         14             Karnataka  South
14         15            Tamil Nadu  South
15         16                Kerala  South
16         17               Kolkata   East
17         18           West Bengal   East
18         19                 Bihar   East
19         20                Odisha   East
20         21                 Assam   East
21         22            North East   East

In [29]:
q("""
select count(*) as total_count,
COUNT(DISTINCT plan_id) as distinct_count
FROM plans;
""")

   total_count  distinct_count
0           14              14

In [30]:
q("""
select count(*) as total_count,
COUNT(DISTINCT usage_id) as distinct_count
FROM usage_daily;




""")

   total_count  distinct_count
0      1326739         1326739

In [31]:
q("""
select count(*) as total_count,
COUNT(DISTINCT usage_id) as distinct_count
FROM usage_daily;




""")

   total_count  distinct_count
0      1326739         1326739

In [32]:
q("""
select count(*) as total_count,
COUNT(DISTINCT recharge_id) as distinct_count
FROM recharges;




""")

   total_count  distinct_count
0       408089          408089

In [33]:
q("""
select count(*) as total_count,
COUNT(DISTINCT complaint_id) as distinct_count
FROM complaints;




""")

   total_count  distinct_count
0        26841           26841

In [34]:
q("""select count(*)
from circles c
join customers cu
on c.circle_id = cu.circle_id;""")

   count(*)
0     22000

In [35]:
q("""select count(*)
from circles as c
join customers as cu
on c.circle_id = cu.circle_id;""")

   count(*)
0     22000

In [38]:
q("""SELECT SUM(is_churned = 1 AND churn_date IS NOT NULL) 
               AS left_dated,
            SUM(is_churned = 0 AND churn_date IS NULL) 
               AS STAYED_BLANK
FROM customers;""")

   left_dated  STAYED_BLANK
0        5226         16774